### PR TITLE
Attempt to make Scan Interval configurable

### PR DESCRIPTION
**Pull request by LarsMudde**
After testing and trying I've redone a lot of things, please test and review carefully.
Setup was inspired by: https://aarongodfrey.dev/home%20automation/building_a_home_assistant_custom_component_part_4/ 

Screenshot configure
You can now use the configure button to set the scan interval.

### CODE REVIEW

**Comment by danielrivard** [comment]
Saw this log after changing the sync interval.

`Traceback (most recent call last):
File "/config/custom_components/innova/__init__.py", line 65, in _async_options_updated
hass.config_entries.async_setup_platforms(entry, PLATFORMS)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?`

**Comment by LarsMudde** [comment]
Hi Daniel, thanks for the feedback, I'll check my own logs too, I haven't seen the error myself. I'll try to make time to address it tonight.

**Comment by LarsMudde** [comment]
Hi Daniel, I think I have fixed the error by unloading the existing platforms before re-setting them up during options updates in the _async_options_updated method.

**Review by danielrivard — APPROVED** [review]
I've been using your branch for since Friday, and modified the scan interval a few times without issue. I'll merge it. I may make a few minor changes before preparing a release, but I will generate a release very soon.

**Comment by LarsMudde** [comment]
Thanks Daniel, I appreciate it.

**Pull request merged**
